apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  annotations:
    github.com/project-slug: anitapati/backstage-demo
spec:
  type: other
  lifecycle: unknown
  owner: guests
